// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BottomZone: typeof import('./src/components/index/BottomZone.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MainPage: typeof import('./src/components/index/MainPage.vue')['default']
    MusicInfo: typeof import('./src/components/index/MusicInfo.vue')['default']
    MusicQueue: typeof import('./src/components/MusicQueue.vue')['default']
    NavBar: typeof import('./src/components/index/NavBar.vue')['default']
    PlayControl: typeof import('./src/components/index/PlayControl.vue')['default']
    PlayControlNew1: typeof import('./src/components/index/PlayControlNew1.vue')['default']
    SearchBox: typeof import('./src/components/index/SearchBox.vue')['default']
  }
}

export { }
