// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BannerView: typeof import('./src/components/BannerView.vue')['default']
    BottomZone: typeof import('./src/components/Footer/BottomZone.vue')['default']
    CommentsView: typeof import('./src/components/CommentsView.vue')['default']
    CoverLazy: typeof import('./src/components/CoverLazy.vue')['default']
    CoverView: typeof import('./src/components/CoverView.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MainPage: typeof import('./src/components/MainPage/MainPage.vue')['default']
    MusicInfo: typeof import('./src/components/Footer/MusicInfo.vue')['default']
    MusicQueue: typeof import('./src/components/MusicQueue.vue')['default']
    MusicTable: typeof import('./src/components/MusicTable.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    PlayControl: typeof import('./src/components/Footer/PlayControl.vue')['default']
    SearchBox: typeof import('./src/components/NavBar/SearchBox.vue')['default']
    ShowMore: typeof import('./src/components/ShowMore.vue')['default']
  }
}

export { }
